name: Build PXEngine Release

on:
  push:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake g++ ninja-build

    - name: Build project
      run: cmake --preset release && cmake --build --preset release

    - name: Upload build artifacts (optional)
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: PXEngine-Build
        path: bin/
